app/models.py
# -*- coding: utf-8 -*-

from app import db
from datetime import datetime

import re

from flask_security import UserMixin
from flask_security import RoleMixin

def slugify(string):
    pattern = r'[ˆ\W+]'
    return re.sub(pattern, '-', string.lower())


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()


    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return 'Post {}: {}'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.generate_slug()

    def __repr__(self):
        return '{}'.format(self.name)

    def generate_slug(self):
        if self.name:
            self.slug = slugify(self.name)

# Flask security

roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
                       )

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary='roles_users', backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField, HiddenField

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

class EditForm(PostForm):
    id = HiddenField('id')

app/app.py
from flask import Flask

from config import Configuration

from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate
from flask_migrate import MigrateCommand

from flask_script import Manager

from flask_admin import Admin

from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore
from flask_security import Security

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)

manager.add_command('db', MigrateCommand)

### Admin ###
from models import *

from flask_security import current_user
from flask import redirect
from flask import url_for
from flask import request

from flask_admin import AdminIndexView

class AdminMixin(object):
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))

class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

class AdminView(AdminMixin, ModelView):
    pass

class HomeAdminView(AdminMixin, AdminIndexView):
    pass

class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']

class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']

admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

# Flask security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

app/main.py
from app import app
import view
from app import db
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix = '/blog')

if '__main__' == __name__:
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

from flask_security import login_required

from models import Post, Tag

from .forms import PostForm
from .forms import EditForm

from app import db

posts = Blueprint('posts', __name__, template_folder= 'templates')

@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if 'POST' == request.method:
        title = request.form.get('title', '')
        body = request.form.get('body', '')
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('some error')
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/edit_post.html', form=form)

@posts.route('/edit/<id>', methods=['POST', 'GET'])
@login_required
def edit_post(id):
    post = Post.query.filter(Post.id == id).first()
    if 'POST' == request.method:
        form = EditForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = EditForm(obj=post)
    return render_template('posts/edit_post.html', form=form, post=post)

@posts.route('/')
def index():
    search = request.args.get('search')

    page = request.args.get('page') # type: str
    page = 1 if not (page and page.isdigit()) else int(page) # type: int

    if search:
        posts = Post.query.filter(Post.title.contains(search) | Post.body.contains(search)).order_by(Post.created.desc())
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page, per_page=5)
    return render_template('posts/index.html', pages=pages)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% set title = 'Edit post "' ~ post.title ~ '"' if 'id' in form else 'Create new post' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content_title %}
{{ title }}
{% endblock%}

{% block content %}
<div class="col-sm-8">
    <form action="{{ url_for('posts.edit_post', id=post.id) if 'id' in form else url_for('posts.create_post')}}"
          method="POST">
        {% for field in form %}
        {% if 'id' != field.name %}
        <div class="form-group">
            {{ field.label() }}
            {{ field(class="form-control") }}
        </div>
        {% else %}
        {{ field() }}
        {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}
{% from 'posts/macros.html' import posts_title_list %}

{% set title = 'Search for "' + request.args.get('search') + '"' if (request.args.get('search', false)) else 'Posts list' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content_title %}
{{ title }}
{% endblock%}

{% block content %}
{{ posts_title_list(pages.items) }}
{% if pages.total > 5 %}
<div class="col-md-6">
    <nav>
        <ul class="pagination">
            <li
                    {% if pages.has_prev %}
                    class="page-item"
                    {%else %}
                    class="page-item disabled"
                    {% endif %}
            >
                <a class="page-link" href="./?page={{ pages.prev_num}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% for page in pages.iter_pages() %}
            <li class="page-item {% if page == pages.page %} active {% endif %}"><a class="page-link "
                                                                                    href="./?page={{ page }}">{{ page
                }}</a></li>
            {% endfor %}
            <li
                    {% if pages.has_next %}
                    class="page-item"
                    {%else %}
                    class="page-item disabled"
                    {% endif %}
            >
                <a class="page-link" href="./?page={{ pages.next_num }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
</div>
{% endif %}
{% endblock %}

app/posts/templates/posts/macros.html
{% macro posts_title_list(posts) %}
    <div class="col-sm-12">
        <ul>
            {% for post in posts %}
                <li>
                    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock%}

{% block content %}
        <div class="tags">
        {% for tag in post.tags %}
            <a class="badge badge-danger" href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</a>
        {% endfor %}
    </div>
    <p>{{post.body}}</p>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}
{% from 'posts/macros.html' import posts_title_list %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}"
{% endblock%}

{% block content %}
    <div class="posts">
        {{ posts_title_list(posts) }}
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
    <title>
        {% block title %}
        {% endblock %} | Flask app
    </title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('index')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.index')}}">Blog</a>
            </li>
            {% if current_user.has_role('admin') %}
            <li class="nav-item">
                <a class="nav-link disabled" href="/admin">Admin panel</a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for('posts.index') }}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search"
                   value="{{ request.args.get('search', '') }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="container">
    <h1>
        {% block content_title %}
        {% endblock %}
    </h1>
    <div class="content">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}
    index page
{% endblock %}

{% block content_title %}
    index page content title
{% endblock %}

{% block content %}
    index page content
{% endblock %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes col-sm-12">
    {% for category, message in messages %}
      <div class="alert-{{ category }} alert">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

app/templates/security/login_user.html
{% extends 'base.html' %}
{% from 'security/_macros.html' import render_field_with_errors, render_field %}

{% block title %}
Log in
{% endblock %}

{% block content_title %}
Log in
{% endblock%}

{% block content %}
{% include 'security/_messages.html' %}
<div class="col-sm-6">
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        {{ render_field_with_errors(login_user_form.email, class='form-control') }}
        {{ render_field_with_errors(login_user_form.password, class='form-control') }}
        {{ render_field_with_errors(login_user_form.remember, class='form-control') }}
        {{ render_field(login_user_form.next) }}
        {{ render_field(login_user_form.submit, class='btn btn-primary') }}
    </form>
    {% include "security/_menu.html" %}
</div>
{% endblock %}